#!/usr/bin/env bash
# Regenerate layered Mod SDK shapes from `beskid_analysis` via `beskid_ast_reflect_gen`.
# Run from any cwd; requires the compiler workspace (parent of `crates/`).
set -euo pipefail

COMPILER_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$COMPILER_ROOT"

SDK_BESKID_DIR="corelib/packages/compiler-sdk/src/Beskid"
SDK_COMPILER_DIR="$SDK_BESKID_DIR/Compiler"

run_gen() {
  cargo run -p beskid_ast_reflect_gen --quiet -- "$@"
}

header() {
  cat <<'EOF'
// CHECKED IN: regenerated by packages/compiler-sdk/regen_mod_sdk_surfaces.sh
// Rust sources in beskid_analysis are authoritative; Syntax/Nodes uses concrete helpers (no ReflectStub).
EOF
}

stub() {
  echo
  echo "pub type ReflectStub {}"
  echo
}

write_syntax() {
  # Per-node `.bd` files under Syntax/Nodes/ plus thin Syntax.bd (see beskid_ast_reflect_gen::syntax_nodes).
  run_gen --quiet --workspace "$COMPILER_ROOT" --emit-syntax-sdk "$SDK_BESKID_DIR"
}

write_query() {
  local out="$SDK_COMPILER_DIR/Query.bd"
  {
    header
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Fluent query plans over syntax snapshots for the process phase (lowers to beskid_analysis::query).

EOF
    run_gen --quiet --workspace "$COMPILER_ROOT" --emit-query-facade
  } >"$out"
}

write_diagnostics() {
  local out="$SDK_COMPILER_DIR/Diagnostics.bd"
  {
    header
    run_gen --no-banner --no-reflect-stub --items Severity,SemanticIssueKind \
      crates/beskid_analysis/src/analysis/diagnostics.rs \
      crates/beskid_analysis/src/analysis/diagnostic_kinds.rs
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Construction and reporting of compiler-native diagnostics from mod analyzers.

// Diagnostics facade contract version aligned with platform-spec Beskid.Compiler.Diagnostics hub.
pub string DiagnosticsFacadeVersion() {
    return "0.2.0";
}
EOF
  } >"$out"
}

write_emitter_kind() {
  local out="$SDK_COMPILER_DIR/Emitter/Kind.bd"
  {
    header
    run_gen --no-banner --no-reflect-stub --only-annotated \
      --items ReflectSdkEmitContributionKind,ReflectSdkSyntaxContributionItem \
      crates/beskid_analysis/src/compiler_sdk_reflect.rs
  } >"$out"
}

write_internal_symbol() {
  local out="$SDK_COMPILER_DIR/InternalSymbol.bd"
  {
    header
    run_gen --no-banner --no-reflect-stub --only-annotated \
      --items ReflectSdkInternalSymbolType \
      crates/beskid_analysis/src/compiler_sdk_reflect.rs
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Host reads [InternalSymbol] metadata when building mod.descriptor.json registrations.

/// Describes how a mod entrypoint is exported for AOT host binding.
pub enum InternalSymbolType {
    Callable(InternalSymbolCallable),
}

/// Callable ABI shape: parameter types in Beskid type syntax (schema for marshaling).
/// Return type is inferred from the annotated method signature.
pub type InternalSymbolCallable {
    Beskid.Compiler.Collect.GenerationRequest[] parameters,
}

/// Marks a contract entry method for native export and mod-host scheduling.
pub attribute InternalSymbol(MethodDefinition) {
    symbol: InternalSymbolType,
}

pub string InternalSymbolFacadeVersion() {
    return "0.2.0";
}
EOF
  } >"$out"
}

write_workspace() {
  local out="$SDK_COMPILER_DIR/Workspace.bd"
  {
    header
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Active workspace summary for mod contract entrypoints.

/// One resolved workspace member project visible to mod contracts.
pub type WorkspaceMember {
    string memberId,
    string projectName,
    string projectRoot,
    string sourceRoot,
}

/// Active workspace summary: root path, members, and lockfile identity.
pub type Workspace {
    string rootPath,
    WorkspaceMember[] members,
    string lockHash,
}

pub string WorkspaceFacadeVersion() {
    return "0.1.0";
}
EOF
  } >"$out"
}

write_mod_package() {
  local out="$SDK_COMPILER_DIR/ModPackage.bd"
  {
    header
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Single loaded mod package introspection for mod contract entrypoints.

/// One `(contractId, typeId, entrySymbol)` registration from a loaded mod descriptor.
pub type ModContractRegistration {
    string contractId,
    string typeId,
    string entrySymbol,
}

/// Introspection view of a single loaded mod package in the active compilation.
pub type ModPackage {
    string packageId,
    string packageVersion,
    string projectName,
    string projectRoot,
    string sourceRoot,
    string manifestPath,
    string descriptorPath,
    string[] capabilities,
    ModContractRegistration[] registrations,
}

pub string ModPackageFacadeVersion() {
    return "0.1.0";
}
EOF
  } >"$out"
}

write_mod_catalog() {
  local out="$SDK_COMPILER_DIR/ModCatalog.bd"
  {
    header
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Catalog of mod packages loaded for the active host compilation.

use Beskid.Compiler.ModPackage;

/// Catalog of mod packages loaded for the active host compilation.
pub type ModCatalog {
    ModPackage[] packages,
}

pub string ModCatalogFacadeVersion() {
    return "0.1.0";
}
EOF
  } >"$out"
}

write_collect() {
  local out="$SDK_COMPILER_DIR/Collect.bd"
  {
    header
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Mod packages import these contracts — do not redeclare locally.

use Beskid.Compiler.Compilation;
use Beskid.Compiler.ModCatalog;
use Beskid.Compiler.Workspace;
use Beskid.Syntax.Nodes;

pub type CollectRequest {
    Beskid.Compiler.Compilation compilation,
    Beskid.Compiler.Workspace workspace,
    Beskid.Compiler.ModCatalog mods,
}

pub type CollectTargetSet {
    string[] targetIds,
}

pub type GenerationRequest {
    CollectRequest context,
    CollectTargetSet targets,
}

pub type AnalysisRequest {
    CollectRequest context,
}

pub type AnalysisResult {}
pub type AttributeGenerationRequest {
    CollectRequest context,
}
pub type AttributeDeclarationSet {}
pub type FixError {}

/// One top-level syntax item contributed by a Generator (typed AST, not source text).
pub enum SyntaxContributionItem {
    ContractDefinition(ContractDefinition definition),
    TypeDefinition(TypeDefinition definition),
    FunctionDefinition(FunctionDefinition definition),
}

/// Typed AST payload returned from `Generator.Generate`.
pub type GeneratedSyntaxContribution {
    SyntaxContributionItem[] items,
}

/// Declarative target collection and scope narrowing for a Mod instance.
pub contract Collector {
    CollectTargetSet Collect(CollectRequest request);
}

/// Incremental typed AST contribution entrypoint.
pub contract Generator {
    GeneratedSyntaxContribution Generate(GenerationRequest request);
}

/// Post-semantic diagnostic and rewrite-registration entrypoint.
pub contract Analyzer {
    AnalysisResult Analyze(AnalysisRequest request);
}

/// Typed replacement contract. TSourceNode and TTargetNode are SDK type parameters until contract generics are admitted by the grammar.
pub contract Rewriter {
    Result<TTargetNode, FixError> Rewrite(TSourceNode sourceNode);
}

/// Attribute declarations exported by Mod packages.
pub contract AttributeGenerator {
    AttributeDeclarationSet Attributes(AttributeGenerationRequest request);
}

pub string CollectFacadeVersion() {
    return "0.3.0";
}
EOF
  } >"$out"
}

write_compilation() {
  local out="$SDK_COMPILER_DIR/Compilation.bd"
  {
    header
    run_gen --no-banner --no-reflect-stub --only-annotated \
      --items ReflectSdkCompilationSnapshotPlane \
      crates/beskid_analysis/src/compiler_sdk_reflect.rs
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Handle for the current compilation instance visible to Mod contracts.

/// Active host compilation summary passed to mod contract entrypoints.
pub type Compilation {
    string activeProjectName,
    string activeProjectRoot,
    string targetTriple,
    u64 syntaxGenerationId,
    string entrySourcePath,
    string entrySourceName,
}

// Language / toolchain version token for versioned facades (Mod SDK + platform-spec alignment).
pub string CompilerLanguageVersionToken() {
    return "0.2";
}

// Semantic snapshot family identifier for read-only query surfaces (semantic.snapshot plane).
pub string SemanticSnapshotFamilyToken() {
    return "semantic.snapshot.v1";
}

// Mod SDK compilation surface version (independent of user program language version).
pub string ModSdkCompilationSurfaceVersion() {
    return "0.3.0";
}
EOF
  } >"$out"
}

write_syntax
write_query
write_diagnostics
write_emitter_kind
write_internal_symbol
write_workspace
write_mod_package
write_mod_catalog
write_collect
write_compilation

echo "Wrote Mod SDK surfaces under $COMPILER_ROOT/corelib/packages/compiler-sdk/src/Beskid"
