#!/usr/bin/env bash
# Regenerate layered `Beskid.Compiler.*` shapes from `beskid_analysis` via `beskid_ast_reflect_gen`.
# Run from any cwd; requires the compiler workspace (parent of `crates/`).
set -euo pipefail

COMPILER_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$COMPILER_ROOT"

SDK_DIR="corelib/packages/compiler-sdk/src/Beskid/Compiler"

run_gen() {
  cargo run -p beskid_ast_reflect_gen --quiet -- "$@"
}

header() {
  cat <<'EOF'
// CHECKED IN: regenerated by packages/compiler-sdk/regen_mod_sdk_surfaces.sh
// Rust sources in beskid_analysis are authoritative; stitched hub files below may use ReflectStub for unmapped payloads (the Syntax tree uses concrete Nodes helpers instead).
EOF
}

stub() {
  echo
  echo "pub type ReflectStub {}"
  echo
}

write_syntax() {
  # Per-node `.bd` files under Syntax/Nodes/ plus thin Syntax.bd (see beskid_ast_reflect_gen::syntax_nodes).
  run_gen --quiet --workspace "$COMPILER_ROOT" --emit-syntax-sdk "$SDK_DIR"
}

write_query() {
  local out="$SDK_DIR/Query.bd"
  {
    header
    stub
    run_gen --no-banner --no-reflect-stub --only-annotated \
      --items ReflectSdkNodeKind,ReflectSdkHirNodeKind \
      crates/beskid_analysis/src/compiler_sdk_reflect.rs
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Fluent query plans over syntax (and optional semantic snapshots) for the process phase.

// Query facade contract version aligned with platform-spec Beskid.Compiler.Query hub.
pub string QueryFacadeVersion() {
    return "0.2.0";
}
EOF
  } >"$out"
}

write_diagnostics() {
  local out="$SDK_DIR/Diagnostics.bd"
  {
    header
    stub
    run_gen --no-banner --no-reflect-stub --items Severity,SemanticIssueKind \
      crates/beskid_analysis/src/analysis/diagnostics.rs \
      crates/beskid_analysis/src/analysis/diagnostic_kinds.rs
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Construction and reporting of compiler-native diagnostics from meta items.

// Diagnostics facade contract version aligned with platform-spec Beskid.Compiler.Diagnostics hub.
pub string DiagnosticsFacadeVersion() {
    return "0.2.0";
}
EOF
  } >"$out"
}

write_emit() {
  local out="$SDK_DIR/Emit.bd"
  {
    header
    stub
    run_gen --no-banner --no-reflect-stub --only-annotated \
      --items ReflectSdkEmitContributionKind \
      crates/beskid_analysis/src/compiler_sdk_reflect.rs
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Typed transforms and contributions (no raw-text emit contract).

// Emit facade contract version aligned with platform-spec Beskid.Compiler.Emit hub.
pub string EmitFacadeVersion() {
    return "0.2.0";
}
EOF
  } >"$out"
}

write_process() {
  local out="$SDK_DIR/Process.bd"
  {
    header
    stub
    run_gen --no-banner --no-reflect-stub --only-annotated \
      --items ReflectSdkProcessHookKind \
      crates/beskid_analysis/src/compiler_sdk_reflect.rs
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Named process contexts, lifecycle hooks, and Meta project orchestration metadata.

// Process facade contract version aligned with platform-spec Beskid.Compiler.Process hub.
pub string ProcessFacadeVersion() {
    return "0.2.0";
}
EOF
  } >"$out"
}

write_compilation() {
  local out="$SDK_DIR/Compilation.bd"
  {
    header
    stub
    run_gen --no-banner --no-reflect-stub --only-annotated \
      --items ReflectSdkCompilationSnapshotPlane \
      crates/beskid_analysis/src/compiler_sdk_reflect.rs
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Handle for the current compilation instance (language-meta meta block scope).

// Language / toolchain version token for versioned facades (Mod SDK + platform-spec alignment).
pub string CompilerLanguageVersionToken() {
    return "0.2";
}

// Semantic snapshot family identifier for read-only query surfaces (semantic.snapshot plane).
pub string SemanticSnapshotFamilyToken() {
    return "semantic.snapshot.v1";
}

// Mod SDK compilation surface version (independent of user program language version).
pub string ModSdkCompilationSurfaceVersion() {
    return "0.2.0";
}
EOF
  } >"$out"
}

write_syntax
write_query
write_diagnostics
write_emit
write_process
write_compilation

echo "Wrote Mod SDK surfaces under $COMPILER_ROOT/$SDK_DIR"
