#!/usr/bin/env bash
# Regenerate layered Mod SDK shapes from `beskid_analysis` via `beskid_ast_reflect_gen`.
# Run from any cwd; requires the compiler workspace (parent of `crates/`).
set -euo pipefail

COMPILER_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$COMPILER_ROOT"

SDK_BESKID_DIR="corelib/packages/compiler-sdk/src/Beskid"
SDK_COMPILER_DIR="$SDK_BESKID_DIR/Compiler"

run_gen() {
  cargo run -p beskid_ast_reflect_gen --quiet -- "$@"
}

header() {
  cat <<'EOF'
// CHECKED IN: regenerated by packages/compiler-sdk/regen_mod_sdk_surfaces.sh
// Rust sources in beskid_analysis are authoritative; Syntax/Nodes uses concrete helpers (no ReflectStub).
EOF
}

stub() {
  echo
  echo "pub type ReflectStub {}"
  echo
}

write_syntax() {
  # Per-node `.bd` files under Syntax/Nodes/ plus thin Syntax.bd (see beskid_ast_reflect_gen::syntax_nodes).
  run_gen --quiet --workspace "$COMPILER_ROOT" --emit-syntax-sdk "$SDK_BESKID_DIR"
}

write_query() {
  local out="$SDK_COMPILER_DIR/Query.bd"
  {
    header
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Fluent query plans over syntax snapshots for the process phase (lowers to beskid_analysis::query).

EOF
    run_gen --quiet --workspace "$COMPILER_ROOT" --emit-query-facade
  } >"$out"
}

write_diagnostics() {
  local out="$SDK_COMPILER_DIR/Diagnostics.bd"
  {
    header
    run_gen --no-banner --no-reflect-stub --items Severity,SemanticIssueKind \
      crates/beskid_analysis/src/analysis/diagnostics.rs \
      crates/beskid_analysis/src/analysis/diagnostic_kinds.rs
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Construction and reporting of compiler-native diagnostics from mod analyzers.

// Diagnostics facade contract version aligned with platform-spec Beskid.Compiler.Diagnostics hub.
pub string DiagnosticsFacadeVersion() {
    return "0.2.0";
}
EOF
  } >"$out"
}

write_typed_emitter() {
  local out="$SDK_COMPILER_DIR/TypedEmitter.bd"
  {
    header
    run_gen --no-banner --no-reflect-stub --only-annotated \
      --items ReflectSdkEmitContributionKind \
      crates/beskid_analysis/src/compiler_sdk_reflect.rs
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Typed transforms and contributions (no raw-text emit contract).

// Typed emitter facade contract version aligned with platform-spec Beskid.Compiler.TypedEmitter hub.
pub string TypedEmitterFacadeVersion() {
    return "0.2.0";
}
EOF
  } >"$out"
}

write_collect() {
  local out="$SDK_COMPILER_DIR/Collect.bd"
  {
    header
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Contract entrypoints discovered from AOT-compiled Mod packages.

pub type CollectRequest {}
pub type CollectTargetSet {}
pub type GenerationRequest {}
pub type GeneratedSyntaxContribution {}
pub type AnalysisRequest {}
pub type AnalysisResult {}
pub type AttributeGenerationRequest {}
pub type AttributeDeclarationSet {}
pub type FixError {}

/// Declarative target collection and scope narrowing for a Mod instance.
pub contract Collector {
    CollectTargetSet Collect(CollectRequest request);
}

/// Incremental typed AST contribution entrypoint.
pub contract Generator {
    GeneratedSyntaxContribution Generate(GenerationRequest request);
}

/// Post-semantic diagnostic and rewrite-registration entrypoint.
pub contract Analyzer {
    AnalysisResult Analyze(AnalysisRequest request);
}

/// Typed replacement contract. TSourceNode and TTargetNode are SDK type parameters until contract generics are admitted by the grammar.
pub contract Rewriter {
    Result<TTargetNode, FixError> Rewrite(TSourceNode sourceNode);
}

/// Attribute declarations exported by Mod packages.
pub contract AttributeGenerator {
    AttributeDeclarationSet Attributes(AttributeGenerationRequest request);
}

// Collect facade contract version aligned with platform-spec Beskid.Compiler.Collect hub.
pub string CollectFacadeVersion() {
    return "0.2.0";
}
EOF
  } >"$out"
}

write_compilation() {
  local out="$SDK_COMPILER_DIR/Compilation.bd"
  {
    header
    run_gen --no-banner --no-reflect-stub --only-annotated \
      --items ReflectSdkCompilationSnapshotPlane \
      crates/beskid_analysis/src/compiler_sdk_reflect.rs
    cat <<'EOF'

// Hand-maintained facade ------------------------------------------------------
// Handle for the current compilation instance visible to Mod contracts.

// Language / toolchain version token for versioned facades (Mod SDK + platform-spec alignment).
pub string CompilerLanguageVersionToken() {
    return "0.2";
}

// Semantic snapshot family identifier for read-only query surfaces (semantic.snapshot plane).
pub string SemanticSnapshotFamilyToken() {
    return "semantic.snapshot.v1";
}

// Mod SDK compilation surface version (independent of user program language version).
pub string ModSdkCompilationSurfaceVersion() {
    return "0.2.0";
}
EOF
  } >"$out"
}

write_syntax
write_query
write_diagnostics
write_typed_emitter
write_collect
write_compilation

echo "Wrote Mod SDK surfaces under $COMPILER_ROOT/corelib/packages/compiler-sdk/src/Beskid"
